version: '3.7'
services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Simple2B
    ports:
      - 127.0.0.1:${PGADMIN_PORT}:80
      - 127.0.0.1:${PGADMIN_HTTPS}:443

  admin:
    build: .
    restart: always
    command: bash ./start_admin.sh
    ports:
      - 127.0.0.1:${LOCAL_ADMIN_PORT}:5000
    volumes:
      - .:/app
    depends_on:
      - db

  api:
    build: .
    restart: always
    command: bash ./start_server.sh
    ports:
      - 127.0.0.1:${LOCAL_API_PORT}:80
    volumes:
      - .:/app
    depends_on:
      - db

  front:
    image: nginx:stable-alpine
    restart: always
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT}:80
    volumes:
      - ${FRONTEND_PATH}:/usr/share/nginx/html
      - ${FRONTEND_CONFIG}:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  db_data:
