"""empty message

Revision ID: 372998a49bca
Revises: 468a144c66d6
Create Date: 2021-10-05 16:10:57.933143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372998a49bca'
down_revision = '468a144c66d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('referring', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'referring')
    # ### end Alembic commands ###
