"""empty message

Revision ID: 4d139412cd47
Revises: 352abb027016
Create Date: 2022-03-24 11:01:45.925852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d139412cd47'
down_revision = '352abb027016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_phone', table_name='clients')
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.create_index('ix_clients_phone', 'clients', ['phone'], unique=False)
    # ### end Alembic commands ###
