"""empty message

Revision ID: 4e64c16bb97f
Revises: 9026e79eae25
Create Date: 2021-12-02 13:52:58.990350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e64c16bb97f"
down_revision = "9026e79eae25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "careplans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("care_plan", sa.String(length=128), nullable=True),
        sa.Column("frequency", sa.String(length=128), nullable=True),
        sa.Column("progress_date", sa.DateTime(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("doctor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_careplans_id"), "careplans", ["id"], unique=False)
    op.add_column(
        "info_care_plans", sa.Column("doctor_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "info_care_plans", "doctors", ["doctor_id"], ["id"])
    op.add_column(
        "info_frequencies", sa.Column("doctor_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "info_frequencies", "doctors", ["doctor_id"], ["id"])
    op.add_column("tests", sa.Column("care_plan_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tests", "careplans", ["care_plan_id"], ["id"])
    op.drop_column("tests", "care_plan")
    op.drop_column("tests", "frequency")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tests",
        sa.Column(
            "frequency", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "tests",
        sa.Column(
            "care_plan", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "tests", type_="foreignkey")
    op.drop_column("tests", "care_plan_id")
    op.drop_constraint(None, "info_frequencies", type_="foreignkey")
    op.drop_column("info_frequencies", "doctor_id")
    op.drop_constraint(None, "info_care_plans", type_="foreignkey")
    op.drop_column("info_care_plans", "doctor_id")
    op.drop_index(op.f("ix_careplans_id"), table_name="careplans")
    op.drop_table("careplans")
    # ### end Alembic commands ###
