"""empty message

Revision ID: 4f3a5a86655a
Revises: ce1cee954334
Create Date: 2021-12-16 13:00:13.700475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3a5a86655a'
down_revision = 'ce1cee954334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('subscription_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billings', 'subscription_quantity')
    # ### end Alembic commands ###
