"""empty message

Revision ID: 588fee996f3b
Revises: 62893e564788
Create Date: 2021-12-01 14:30:19.564954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588fee996f3b'
down_revision = '62893e564788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careplans', sa.Column('progress_date', sa.DateTime(), nullable=True))
    op.drop_column('careplans', 'progress_test_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careplans', sa.Column('progress_test_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('careplans', 'progress_date')
    # ### end Alembic commands ###
