"""empty message

Revision ID: 7a136c4cad69
Revises: 418a52507064
Create Date: 2022-03-15 18:04:55.679917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a136c4cad69'
down_revision = '418a52507064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('req_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'req_date')
    # ### end Alembic commands ###
