"""empty message

Revision ID: a5dc50d00b70
Revises: ba9d25307f5e
Create Date: 2022-03-24 11:16:33.962931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5dc50d00b70'
down_revision = 'ba9d25307f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('req_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'req_date')
    # ### end Alembic commands ###
