"""empty message

Revision ID: aea2d89a6f9e
Revises: cd2c60967bfc
Create Date: 2022-04-28 09:11:04.369710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea2d89a6f9e'
down_revision = 'cd2c60967bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_care_plans', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'info_care_plans', 'clients', ['client_id'], ['id'])
    op.add_column('info_frequencies', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'info_frequencies', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'info_frequencies', type_='foreignkey')
    op.drop_column('info_frequencies', 'client_id')
    op.drop_constraint(None, 'info_care_plans', type_='foreignkey')
    op.drop_column('info_care_plans', 'client_id')
    # ### end Alembic commands ###
