"""empty message

Revision ID: b6f5ce3efbef
Revises: 4f3a5a86655a
Create Date: 2021-12-16 14:24:08.653437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f5ce3efbef'
down_revision = '4f3a5a86655a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('subscription_interval', sa.String(length=128), nullable=True))
    op.add_column('billings', sa.Column('subscription_interval_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billings', 'subscription_interval_count')
    op.drop_column('billings', 'subscription_interval')
    # ### end Alembic commands ###
