"""empty message

Revision ID: ba9d25307f5e
Revises: 4d139412cd47
Create Date: 2022-03-24 11:15:41.104893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9d25307f5e'
down_revision = '4d139412cd47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('req_date', sa.DateTime(), nullable=True))
    op.drop_index('ix_clients_phone', table_name='clients')
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.create_index('ix_clients_phone', 'clients', ['phone'], unique=False)
    op.drop_column('clients', 'req_date')
    # ### end Alembic commands ###
