"""empty message

Revision ID: bf84f67074e1
Revises: 7a136c4cad69
Create Date: 2022-03-22 09:05:25.440005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf84f67074e1'
down_revision = '7a136c4cad69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_email', table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.drop_index('ix_clients_phone', table_name='clients')
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=True)
    op.drop_column('clients', 'req_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('req_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.create_index('ix_clients_phone', 'clients', ['phone'], unique=False)
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_index('ix_clients_email', 'clients', ['email'], unique=False)
    # ### end Alembic commands ###
