"""empty message

Revision ID: c2c6dc34c851
Revises: efd0c59b0b43
Create Date: 2021-11-24 11:52:14.786610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c6dc34c851'
down_revision = 'efd0c59b0b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('consent_diagnostic_procedures', sa.Boolean(), nullable=True))
    op.drop_column('clients', 'relationship_child')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('relationship_child', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'consent_diagnostic_procedures')
    # ### end Alembic commands ###
