"""empty message

Revision ID: cd2c60967bfc
Revises: a5dc50d00b70
Create Date: 2022-04-03 07:46:42.715008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd2c60967bfc"
down_revision = "a5dc50d00b70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consults",
        sa.Column("id", sa.Integer(), nullable=False),  # Noqa E128
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("consult", sa.String(length=128), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("doctor_id", sa.Integer(), nullable=True),
        sa.Column("visit_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consults_id"), "consults", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_consults_id"), table_name="consults")
    op.drop_table("consults")
    # ### end Alembic commands ###
